################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
CPP_SRCS += \
../lib/src/array_del.cpp \
../lib/src/array_new.cpp \
../lib/src/array_nodel.cpp \
../lib/src/array_nonew.cpp \
../lib/src/array_pdel.cpp \
../lib/src/array_pnew.cpp \
../lib/src/delete.cpp \
../lib/src/delnothrow.cpp \
../lib/src/dtor_list.cpp \
../lib/src/eh_util.cpp \
../lib/src/error.cpp \
../lib/src/fiopen.cpp \
../lib/src/guard.cpp \
../lib/src/iomanip.cpp \
../lib/src/ios.cpp \
../lib/src/iostream.cpp \
../lib/src/limits.cpp \
../lib/src/locale.cpp \
../lib/src/locale0.cpp \
../lib/src/memzero.cpp \
../lib/src/new_.cpp \
../lib/src/newhandler.cpp \
../lib/src/newnothrow.cpp \
../lib/src/nothrow.cpp \
../lib/src/placedel.cpp \
../lib/src/placenew.cpp \
../lib/src/pure_virt.cpp \
../lib/src/raisehan.cpp \
../lib/src/rtti.cpp \
../lib/src/set_new.cpp \
../lib/src/string.cpp \
../lib/src/strstrea.cpp \
../lib/src/throw.cpp \
../lib/src/throw_edg.cpp \
../lib/src/typeinfo_.cpp \
../lib/src/vars.cpp \
../lib/src/vec_cctor.cpp \
../lib/src/vec_newdel.cpp \
../lib/src/vla_alloc.cpp \
../lib/src/wiostrea.cpp \
../lib/src/wlocale.cpp \
../lib/src/xfpostox.cpp \
../lib/src/xlocale.cpp \
../lib/src/xlocinfo.cpp 

ASM_SRCS += \
../lib/src/IQ.asm \
../lib/src/IQxmpy.asm \
../lib/src/abstract.asm \
../lib/src/boot.asm \
../lib/src/cpy_utils.asm \
../lib/src/epilog.asm \
../lib/src/farsetjmp.asm \
../lib/src/fd_add.asm \
../lib/src/fd_cmp.asm \
../lib/src/fd_div.asm \
../lib/src/fd_mpy.asm \
../lib/src/fd_neg.asm \
../lib/src/fd_sub.asm \
../lib/src/fd_tofs.asm \
../lib/src/fd_toi.asm \
../lib/src/fd_tol.asm \
../lib/src/fd_toll.asm \
../lib/src/fd_tou.asm \
../lib/src/fd_toul.asm \
../lib/src/fd_toull.asm \
../lib/src/fs_add.asm \
../lib/src/fs_cmp.asm \
../lib/src/fs_div.asm \
../lib/src/fs_mpy.asm \
../lib/src/fs_neg.asm \
../lib/src/fs_tofd.asm \
../lib/src/fs_toi.asm \
../lib/src/fs_tol.asm \
../lib/src/fs_toll.asm \
../lib/src/fs_tou.asm \
../lib/src/fs_toul.asm \
../lib/src/fs_toull.asm \
../lib/src/i_div.asm \
../lib/src/i_tofd.asm \
../lib/src/i_tofs.asm \
../lib/src/l_div.asm \
../lib/src/l_lsl.asm \
../lib/src/l_lsr.asm \
../lib/src/l_mpy.asm \
../lib/src/l_tofd.asm \
../lib/src/l_tofs.asm \
../lib/src/ll_abs.asm \
../lib/src/ll_aox.asm \
../lib/src/ll_cmp.asm \
../lib/src/ll_div.asm \
../lib/src/ll_mpy.asm \
../lib/src/ll_tofd.asm \
../lib/src/ll_tofs.asm \
../lib/src/prolog.asm \
../lib/src/setjmp.asm \
../lib/src/u_div.asm \
../lib/src/u_tofd.asm \
../lib/src/u_tofs.asm \
../lib/src/ul_lsr.asm \
../lib/src/ul_tofd.asm \
../lib/src/ul_tofs.asm \
../lib/src/ull_tofd.asm \
../lib/src/ull_tofs.asm 

C_SRCS += \
../lib/src/_bufread.c \
../lib/src/_data_synch.c \
../lib/src/_io_perm.c \
../lib/src/_lock.c \
../lib/src/_log.c \
../lib/src/_mutex.c \
../lib/src/_printfi.c \
../lib/src/_printfi_min.c \
../lib/src/_printfi_nf.c \
../lib/src/_pthread.c \
../lib/src/_scanfi.c \
../lib/src/_scanfi_min.c \
../lib/src/_scanfi_nf.c \
../lib/src/_tvaltostr.c \
../lib/src/abs.c \
../lib/src/acos.c \
../lib/src/ankmsg.c \
../lib/src/args_main.c \
../lib/src/asctime.c \
../lib/src/asin.c \
../lib/src/assert.c \
../lib/src/atan.c \
../lib/src/atan2.c \
../lib/src/atexit.c \
../lib/src/atof.c \
../lib/src/atoi.c \
../lib/src/atol.c \
../lib/src/atoll.c \
../lib/src/bcmp.c \
../lib/src/bcopy.c \
../lib/src/bsearch.c \
../lib/src/bzero.c \
../lib/src/clearerr.c \
../lib/src/clock.c \
../lib/src/cos.c \
../lib/src/cosh.c \
../lib/src/cpy_tbl.c \
../lib/src/ctime_.c \
../lib/src/ctype.c \
../lib/src/defs.c \
../lib/src/difftime.c \
../lib/src/div.c \
../lib/src/ecvt.c \
../lib/src/errno.c \
../lib/src/exit.c \
../lib/src/exp.c \
../lib/src/fabs.c \
../lib/src/far_cpy_tbl.c \
../lib/src/faratof.c \
../lib/src/faratoi.c \
../lib/src/farbsearch.c \
../lib/src/farfrexp.c \
../lib/src/farltoa.c \
../lib/src/farmemchr.c \
../lib/src/farmemcmp.c \
../lib/src/farmemmov.c \
../lib/src/farmemory.c \
../lib/src/farmemset.c \
../lib/src/farmodf.c \
../lib/src/farqsort.c \
../lib/src/farstrcat.c \
../lib/src/farstrchr.c \
../lib/src/farstrcmp.c \
../lib/src/farstrcoll.c \
../lib/src/farstrcpy.c \
../lib/src/farstrcspn.c \
../lib/src/farstrerror.c \
../lib/src/farstrlen.c \
../lib/src/farstrncat.c \
../lib/src/farstrncmp.c \
../lib/src/farstrncpy.c \
../lib/src/farstrpbrk.c \
../lib/src/farstrrchr.c \
../lib/src/farstrspn.c \
../lib/src/farstrstr.c \
../lib/src/farstrtod.c \
../lib/src/farstrtok.c \
../lib/src/farstrtol.c \
../lib/src/farstrtold.c \
../lib/src/farstrtoll.c \
../lib/src/farstrtoul.c \
../lib/src/farstrtoull.c \
../lib/src/farstrxfrm.c \
../lib/src/fclose.c \
../lib/src/fcvt.c \
../lib/src/feof.c \
../lib/src/ferror.c \
../lib/src/fflush.c \
../lib/src/ffs.c \
../lib/src/fgetc.c \
../lib/src/fgetpos.c \
../lib/src/fgets.c \
../lib/src/fmod.c \
../lib/src/fopen.c \
../lib/src/fprintf.c \
../lib/src/fputc.c \
../lib/src/fputs.c \
../lib/src/fread.c \
../lib/src/frexp.c \
../lib/src/fscanf.c \
../lib/src/fseek.c \
../lib/src/fsetpos.c \
../lib/src/ftell.c \
../lib/src/fwide.c \
../lib/src/fwrite.c \
../lib/src/getenv.c \
../lib/src/gmtime.c \
../lib/src/imaxabs.c \
../lib/src/imaxdiv.c \
../lib/src/index.c \
../lib/src/isalnum.c \
../lib/src/isalpha.c \
../lib/src/isascii.c \
../lib/src/iscntrl.c \
../lib/src/isdigit.c \
../lib/src/isgraph.c \
../lib/src/islower.c \
../lib/src/isprint.c \
../lib/src/ispunct.c \
../lib/src/isspace.c \
../lib/src/isupper.c \
../lib/src/isxdigit.c \
../lib/src/ldexp.c \
../lib/src/lldiv.c \
../lib/src/localtim.c \
../lib/src/log.c \
../lib/src/log10.c \
../lib/src/lowlev.c \
../lib/src/ltoa.c \
../lib/src/memccpy.c \
../lib/src/memchr.c \
../lib/src/memcmp.c \
../lib/src/memcpy.c \
../lib/src/memcpy_ff.c \
../lib/src/memcpy_fn.c \
../lib/src/memcpy_nf.c \
../lib/src/memcpy_nn.c \
../lib/src/memmov.c \
../lib/src/memory.c \
../lib/src/memset.c \
../lib/src/mktime.c \
../lib/src/modf.c \
../lib/src/multibyte.c \
../lib/src/perror.c \
../lib/src/pow.c \
../lib/src/printf.c \
../lib/src/qsort.c \
../lib/src/raise.c \
../lib/src/rand.c \
../lib/src/remove.c \
../lib/src/rewind.c \
../lib/src/rindex.c \
../lib/src/setbuf.c \
../lib/src/setlocale.c \
../lib/src/setvbuf.c \
../lib/src/signal.c \
../lib/src/sin.c \
../lib/src/sinh.c \
../lib/src/sinit.c \
../lib/src/snprintf.c \
../lib/src/sprintf.c \
../lib/src/sqrt.c \
../lib/src/sscanf.c \
../lib/src/stox.c \
../lib/src/strcasecmp.c \
../lib/src/strcat.c \
../lib/src/strchr.c \
../lib/src/strcmp.c \
../lib/src/strcoll.c \
../lib/src/strcpy.c \
../lib/src/strcspn.c \
../lib/src/strdup.c \
../lib/src/strerror.c \
../lib/src/strftime.c \
../lib/src/strlen.c \
../lib/src/strncasecmp.c \
../lib/src/strncat.c \
../lib/src/strncmp.c \
../lib/src/strncpy.c \
../lib/src/strpbrk.c \
../lib/src/strrchr.c \
../lib/src/strspn.c \
../lib/src/strstr.c \
../lib/src/strtod.c \
../lib/src/strtoimax.c \
../lib/src/strtok.c \
../lib/src/strtol.c \
../lib/src/strtold.c \
../lib/src/strtoll.c \
../lib/src/strtoul.c \
../lib/src/strtoull.c \
../lib/src/strtoumax.c \
../lib/src/strxfrm.c \
../lib/src/tan.c \
../lib/src/tanh.c \
../lib/src/time.c \
../lib/src/tmpfile.c \
../lib/src/tmpnam.c \
../lib/src/tmzone.c \
../lib/src/toascii.c \
../lib/src/tolower.c \
../lib/src/toupper.c \
../lib/src/trgdrv.c \
../lib/src/ungetc.c \
../lib/src/vfprintf.c \
../lib/src/vprintf.c \
../lib/src/vsnprintf.c \
../lib/src/vsprintf.c \
../lib/src/wctype.c 

OBJS += \
./lib/src/IQ.obj \
./lib/src/IQxmpy.obj \
./lib/src/_bufread.obj \
./lib/src/_data_synch.obj \
./lib/src/_io_perm.obj \
./lib/src/_lock.obj \
./lib/src/_log.obj \
./lib/src/_mutex.obj \
./lib/src/_printfi.obj \
./lib/src/_printfi_min.obj \
./lib/src/_printfi_nf.obj \
./lib/src/_pthread.obj \
./lib/src/_scanfi.obj \
./lib/src/_scanfi_min.obj \
./lib/src/_scanfi_nf.obj \
./lib/src/_tvaltostr.obj \
./lib/src/abs.obj \
./lib/src/abstract.obj \
./lib/src/acos.obj \
./lib/src/ankmsg.obj \
./lib/src/args_main.obj \
./lib/src/array_del.obj \
./lib/src/array_new.obj \
./lib/src/array_nodel.obj \
./lib/src/array_nonew.obj \
./lib/src/array_pdel.obj \
./lib/src/array_pnew.obj \
./lib/src/asctime.obj \
./lib/src/asin.obj \
./lib/src/assert.obj \
./lib/src/atan.obj \
./lib/src/atan2.obj \
./lib/src/atexit.obj \
./lib/src/atof.obj \
./lib/src/atoi.obj \
./lib/src/atol.obj \
./lib/src/atoll.obj \
./lib/src/bcmp.obj \
./lib/src/bcopy.obj \
./lib/src/boot.obj \
./lib/src/bsearch.obj \
./lib/src/bzero.obj \
./lib/src/clearerr.obj \
./lib/src/clock.obj \
./lib/src/cos.obj \
./lib/src/cosh.obj \
./lib/src/cpy_tbl.obj \
./lib/src/cpy_utils.obj \
./lib/src/ctime_.obj \
./lib/src/ctype.obj \
./lib/src/defs.obj \
./lib/src/delete.obj \
./lib/src/delnothrow.obj \
./lib/src/difftime.obj \
./lib/src/div.obj \
./lib/src/dtor_list.obj \
./lib/src/ecvt.obj \
./lib/src/eh_util.obj \
./lib/src/epilog.obj \
./lib/src/errno.obj \
./lib/src/error.obj \
./lib/src/exit.obj \
./lib/src/exp.obj \
./lib/src/fabs.obj \
./lib/src/far_cpy_tbl.obj \
./lib/src/faratof.obj \
./lib/src/faratoi.obj \
./lib/src/farbsearch.obj \
./lib/src/farfrexp.obj \
./lib/src/farltoa.obj \
./lib/src/farmemchr.obj \
./lib/src/farmemcmp.obj \
./lib/src/farmemmov.obj \
./lib/src/farmemory.obj \
./lib/src/farmemset.obj \
./lib/src/farmodf.obj \
./lib/src/farqsort.obj \
./lib/src/farsetjmp.obj \
./lib/src/farstrcat.obj \
./lib/src/farstrchr.obj \
./lib/src/farstrcmp.obj \
./lib/src/farstrcoll.obj \
./lib/src/farstrcpy.obj \
./lib/src/farstrcspn.obj \
./lib/src/farstrerror.obj \
./lib/src/farstrlen.obj \
./lib/src/farstrncat.obj \
./lib/src/farstrncmp.obj \
./lib/src/farstrncpy.obj \
./lib/src/farstrpbrk.obj \
./lib/src/farstrrchr.obj \
./lib/src/farstrspn.obj \
./lib/src/farstrstr.obj \
./lib/src/farstrtod.obj \
./lib/src/farstrtok.obj \
./lib/src/farstrtol.obj \
./lib/src/farstrtold.obj \
./lib/src/farstrtoll.obj \
./lib/src/farstrtoul.obj \
./lib/src/farstrtoull.obj \
./lib/src/farstrxfrm.obj \
./lib/src/fclose.obj \
./lib/src/fcvt.obj \
./lib/src/fd_add.obj \
./lib/src/fd_cmp.obj \
./lib/src/fd_div.obj \
./lib/src/fd_mpy.obj \
./lib/src/fd_neg.obj \
./lib/src/fd_sub.obj \
./lib/src/fd_tofs.obj \
./lib/src/fd_toi.obj \
./lib/src/fd_tol.obj \
./lib/src/fd_toll.obj \
./lib/src/fd_tou.obj \
./lib/src/fd_toul.obj \
./lib/src/fd_toull.obj \
./lib/src/feof.obj \
./lib/src/ferror.obj \
./lib/src/fflush.obj \
./lib/src/ffs.obj \
./lib/src/fgetc.obj \
./lib/src/fgetpos.obj \
./lib/src/fgets.obj \
./lib/src/fiopen.obj \
./lib/src/fmod.obj \
./lib/src/fopen.obj \
./lib/src/fprintf.obj \
./lib/src/fputc.obj \
./lib/src/fputs.obj \
./lib/src/fread.obj \
./lib/src/frexp.obj \
./lib/src/fs_add.obj \
./lib/src/fs_cmp.obj \
./lib/src/fs_div.obj \
./lib/src/fs_mpy.obj \
./lib/src/fs_neg.obj \
./lib/src/fs_tofd.obj \
./lib/src/fs_toi.obj \
./lib/src/fs_tol.obj \
./lib/src/fs_toll.obj \
./lib/src/fs_tou.obj \
./lib/src/fs_toul.obj \
./lib/src/fs_toull.obj \
./lib/src/fscanf.obj \
./lib/src/fseek.obj \
./lib/src/fsetpos.obj \
./lib/src/ftell.obj \
./lib/src/fwide.obj \
./lib/src/fwrite.obj \
./lib/src/getenv.obj \
./lib/src/gmtime.obj \
./lib/src/guard.obj \
./lib/src/i_div.obj \
./lib/src/i_tofd.obj \
./lib/src/i_tofs.obj \
./lib/src/imaxabs.obj \
./lib/src/imaxdiv.obj \
./lib/src/index.obj \
./lib/src/iomanip.obj \
./lib/src/ios.obj \
./lib/src/iostream.obj \
./lib/src/isalnum.obj \
./lib/src/isalpha.obj \
./lib/src/isascii.obj \
./lib/src/iscntrl.obj \
./lib/src/isdigit.obj \
./lib/src/isgraph.obj \
./lib/src/islower.obj \
./lib/src/isprint.obj \
./lib/src/ispunct.obj \
./lib/src/isspace.obj \
./lib/src/isupper.obj \
./lib/src/isxdigit.obj \
./lib/src/l_div.obj \
./lib/src/l_lsl.obj \
./lib/src/l_lsr.obj \
./lib/src/l_mpy.obj \
./lib/src/l_tofd.obj \
./lib/src/l_tofs.obj \
./lib/src/ldexp.obj \
./lib/src/limits.obj \
./lib/src/ll_abs.obj \
./lib/src/ll_aox.obj \
./lib/src/ll_cmp.obj \
./lib/src/ll_div.obj \
./lib/src/ll_mpy.obj \
./lib/src/ll_tofd.obj \
./lib/src/ll_tofs.obj \
./lib/src/lldiv.obj \
./lib/src/locale.obj \
./lib/src/locale0.obj \
./lib/src/localtim.obj \
./lib/src/log.obj \
./lib/src/log10.obj \
./lib/src/lowlev.obj \
./lib/src/ltoa.obj \
./lib/src/memccpy.obj \
./lib/src/memchr.obj \
./lib/src/memcmp.obj \
./lib/src/memcpy.obj \
./lib/src/memcpy_ff.obj \
./lib/src/memcpy_fn.obj \
./lib/src/memcpy_nf.obj \
./lib/src/memcpy_nn.obj \
./lib/src/memmov.obj \
./lib/src/memory.obj \
./lib/src/memset.obj \
./lib/src/memzero.obj \
./lib/src/mktime.obj \
./lib/src/modf.obj \
./lib/src/multibyte.obj \
./lib/src/new_.obj \
./lib/src/newhandler.obj \
./lib/src/newnothrow.obj \
./lib/src/nothrow.obj \
./lib/src/perror.obj \
./lib/src/placedel.obj \
./lib/src/placenew.obj \
./lib/src/pow.obj \
./lib/src/printf.obj \
./lib/src/prolog.obj \
./lib/src/pure_virt.obj \
./lib/src/qsort.obj \
./lib/src/raise.obj \
./lib/src/raisehan.obj \
./lib/src/rand.obj \
./lib/src/remove.obj \
./lib/src/rewind.obj \
./lib/src/rindex.obj \
./lib/src/rtti.obj \
./lib/src/set_new.obj \
./lib/src/setbuf.obj \
./lib/src/setjmp.obj \
./lib/src/setlocale.obj \
./lib/src/setvbuf.obj \
./lib/src/signal.obj \
./lib/src/sin.obj \
./lib/src/sinh.obj \
./lib/src/sinit.obj \
./lib/src/snprintf.obj \
./lib/src/sprintf.obj \
./lib/src/sqrt.obj \
./lib/src/sscanf.obj \
./lib/src/stox.obj \
./lib/src/strcasecmp.obj \
./lib/src/strcat.obj \
./lib/src/strchr.obj \
./lib/src/strcmp.obj \
./lib/src/strcoll.obj \
./lib/src/strcpy.obj \
./lib/src/strcspn.obj \
./lib/src/strdup.obj \
./lib/src/strerror.obj \
./lib/src/strftime.obj \
./lib/src/string.obj \
./lib/src/strlen.obj \
./lib/src/strncasecmp.obj \
./lib/src/strncat.obj \
./lib/src/strncmp.obj \
./lib/src/strncpy.obj \
./lib/src/strpbrk.obj \
./lib/src/strrchr.obj \
./lib/src/strspn.obj \
./lib/src/strstr.obj \
./lib/src/strstrea.obj \
./lib/src/strtod.obj \
./lib/src/strtoimax.obj \
./lib/src/strtok.obj \
./lib/src/strtol.obj \
./lib/src/strtold.obj \
./lib/src/strtoll.obj \
./lib/src/strtoul.obj \
./lib/src/strtoull.obj \
./lib/src/strtoumax.obj \
./lib/src/strxfrm.obj \
./lib/src/tan.obj \
./lib/src/tanh.obj \
./lib/src/throw.obj \
./lib/src/throw_edg.obj \
./lib/src/time.obj \
./lib/src/tmpfile.obj \
./lib/src/tmpnam.obj \
./lib/src/tmzone.obj \
./lib/src/toascii.obj \
./lib/src/tolower.obj \
./lib/src/toupper.obj \
./lib/src/trgdrv.obj \
./lib/src/typeinfo_.obj \
./lib/src/u_div.obj \
./lib/src/u_tofd.obj \
./lib/src/u_tofs.obj \
./lib/src/ul_lsr.obj \
./lib/src/ul_tofd.obj \
./lib/src/ul_tofs.obj \
./lib/src/ull_tofd.obj \
./lib/src/ull_tofs.obj \
./lib/src/ungetc.obj \
./lib/src/vars.obj \
./lib/src/vec_cctor.obj \
./lib/src/vec_newdel.obj \
./lib/src/vfprintf.obj \
./lib/src/vla_alloc.obj \
./lib/src/vprintf.obj \
./lib/src/vsnprintf.obj \
./lib/src/vsprintf.obj \
./lib/src/wctype.obj \
./lib/src/wiostrea.obj \
./lib/src/wlocale.obj \
./lib/src/xfpostox.obj \
./lib/src/xlocale.obj \
./lib/src/xlocinfo.obj 

ASM_DEPS += \
./lib/src/IQ.pp \
./lib/src/IQxmpy.pp \
./lib/src/abstract.pp \
./lib/src/boot.pp \
./lib/src/cpy_utils.pp \
./lib/src/epilog.pp \
./lib/src/farsetjmp.pp \
./lib/src/fd_add.pp \
./lib/src/fd_cmp.pp \
./lib/src/fd_div.pp \
./lib/src/fd_mpy.pp \
./lib/src/fd_neg.pp \
./lib/src/fd_sub.pp \
./lib/src/fd_tofs.pp \
./lib/src/fd_toi.pp \
./lib/src/fd_tol.pp \
./lib/src/fd_toll.pp \
./lib/src/fd_tou.pp \
./lib/src/fd_toul.pp \
./lib/src/fd_toull.pp \
./lib/src/fs_add.pp \
./lib/src/fs_cmp.pp \
./lib/src/fs_div.pp \
./lib/src/fs_mpy.pp \
./lib/src/fs_neg.pp \
./lib/src/fs_tofd.pp \
./lib/src/fs_toi.pp \
./lib/src/fs_tol.pp \
./lib/src/fs_toll.pp \
./lib/src/fs_tou.pp \
./lib/src/fs_toul.pp \
./lib/src/fs_toull.pp \
./lib/src/i_div.pp \
./lib/src/i_tofd.pp \
./lib/src/i_tofs.pp \
./lib/src/l_div.pp \
./lib/src/l_lsl.pp \
./lib/src/l_lsr.pp \
./lib/src/l_mpy.pp \
./lib/src/l_tofd.pp \
./lib/src/l_tofs.pp \
./lib/src/ll_abs.pp \
./lib/src/ll_aox.pp \
./lib/src/ll_cmp.pp \
./lib/src/ll_div.pp \
./lib/src/ll_mpy.pp \
./lib/src/ll_tofd.pp \
./lib/src/ll_tofs.pp \
./lib/src/prolog.pp \
./lib/src/setjmp.pp \
./lib/src/u_div.pp \
./lib/src/u_tofd.pp \
./lib/src/u_tofs.pp \
./lib/src/ul_lsr.pp \
./lib/src/ul_tofd.pp \
./lib/src/ul_tofs.pp \
./lib/src/ull_tofd.pp \
./lib/src/ull_tofs.pp 

CPP_DEPS += \
./lib/src/array_del.pp \
./lib/src/array_new.pp \
./lib/src/array_nodel.pp \
./lib/src/array_nonew.pp \
./lib/src/array_pdel.pp \
./lib/src/array_pnew.pp \
./lib/src/delete.pp \
./lib/src/delnothrow.pp \
./lib/src/dtor_list.pp \
./lib/src/eh_util.pp \
./lib/src/error.pp \
./lib/src/fiopen.pp \
./lib/src/guard.pp \
./lib/src/iomanip.pp \
./lib/src/ios.pp \
./lib/src/iostream.pp \
./lib/src/limits.pp \
./lib/src/locale.pp \
./lib/src/locale0.pp \
./lib/src/memzero.pp \
./lib/src/new_.pp \
./lib/src/newhandler.pp \
./lib/src/newnothrow.pp \
./lib/src/nothrow.pp \
./lib/src/placedel.pp \
./lib/src/placenew.pp \
./lib/src/pure_virt.pp \
./lib/src/raisehan.pp \
./lib/src/rtti.pp \
./lib/src/set_new.pp \
./lib/src/string.pp \
./lib/src/strstrea.pp \
./lib/src/throw.pp \
./lib/src/throw_edg.pp \
./lib/src/typeinfo_.pp \
./lib/src/vars.pp \
./lib/src/vec_cctor.pp \
./lib/src/vec_newdel.pp \
./lib/src/vla_alloc.pp \
./lib/src/wiostrea.pp \
./lib/src/wlocale.pp \
./lib/src/xfpostox.pp \
./lib/src/xlocale.pp \
./lib/src/xlocinfo.pp 

C_DEPS += \
./lib/src/_bufread.pp \
./lib/src/_data_synch.pp \
./lib/src/_io_perm.pp \
./lib/src/_lock.pp \
./lib/src/_log.pp \
./lib/src/_mutex.pp \
./lib/src/_printfi.pp \
./lib/src/_printfi_min.pp \
./lib/src/_printfi_nf.pp \
./lib/src/_pthread.pp \
./lib/src/_scanfi.pp \
./lib/src/_scanfi_min.pp \
./lib/src/_scanfi_nf.pp \
./lib/src/_tvaltostr.pp \
./lib/src/abs.pp \
./lib/src/acos.pp \
./lib/src/ankmsg.pp \
./lib/src/args_main.pp \
./lib/src/asctime.pp \
./lib/src/asin.pp \
./lib/src/assert.pp \
./lib/src/atan.pp \
./lib/src/atan2.pp \
./lib/src/atexit.pp \
./lib/src/atof.pp \
./lib/src/atoi.pp \
./lib/src/atol.pp \
./lib/src/atoll.pp \
./lib/src/bcmp.pp \
./lib/src/bcopy.pp \
./lib/src/bsearch.pp \
./lib/src/bzero.pp \
./lib/src/clearerr.pp \
./lib/src/clock.pp \
./lib/src/cos.pp \
./lib/src/cosh.pp \
./lib/src/cpy_tbl.pp \
./lib/src/ctime_.pp \
./lib/src/ctype.pp \
./lib/src/defs.pp \
./lib/src/difftime.pp \
./lib/src/div.pp \
./lib/src/ecvt.pp \
./lib/src/errno.pp \
./lib/src/exit.pp \
./lib/src/exp.pp \
./lib/src/fabs.pp \
./lib/src/far_cpy_tbl.pp \
./lib/src/faratof.pp \
./lib/src/faratoi.pp \
./lib/src/farbsearch.pp \
./lib/src/farfrexp.pp \
./lib/src/farltoa.pp \
./lib/src/farmemchr.pp \
./lib/src/farmemcmp.pp \
./lib/src/farmemmov.pp \
./lib/src/farmemory.pp \
./lib/src/farmemset.pp \
./lib/src/farmodf.pp \
./lib/src/farqsort.pp \
./lib/src/farstrcat.pp \
./lib/src/farstrchr.pp \
./lib/src/farstrcmp.pp \
./lib/src/farstrcoll.pp \
./lib/src/farstrcpy.pp \
./lib/src/farstrcspn.pp \
./lib/src/farstrerror.pp \
./lib/src/farstrlen.pp \
./lib/src/farstrncat.pp \
./lib/src/farstrncmp.pp \
./lib/src/farstrncpy.pp \
./lib/src/farstrpbrk.pp \
./lib/src/farstrrchr.pp \
./lib/src/farstrspn.pp \
./lib/src/farstrstr.pp \
./lib/src/farstrtod.pp \
./lib/src/farstrtok.pp \
./lib/src/farstrtol.pp \
./lib/src/farstrtold.pp \
./lib/src/farstrtoll.pp \
./lib/src/farstrtoul.pp \
./lib/src/farstrtoull.pp \
./lib/src/farstrxfrm.pp \
./lib/src/fclose.pp \
./lib/src/fcvt.pp \
./lib/src/feof.pp \
./lib/src/ferror.pp \
./lib/src/fflush.pp \
./lib/src/ffs.pp \
./lib/src/fgetc.pp \
./lib/src/fgetpos.pp \
./lib/src/fgets.pp \
./lib/src/fmod.pp \
./lib/src/fopen.pp \
./lib/src/fprintf.pp \
./lib/src/fputc.pp \
./lib/src/fputs.pp \
./lib/src/fread.pp \
./lib/src/frexp.pp \
./lib/src/fscanf.pp \
./lib/src/fseek.pp \
./lib/src/fsetpos.pp \
./lib/src/ftell.pp \
./lib/src/fwide.pp \
./lib/src/fwrite.pp \
./lib/src/getenv.pp \
./lib/src/gmtime.pp \
./lib/src/imaxabs.pp \
./lib/src/imaxdiv.pp \
./lib/src/index.pp \
./lib/src/isalnum.pp \
./lib/src/isalpha.pp \
./lib/src/isascii.pp \
./lib/src/iscntrl.pp \
./lib/src/isdigit.pp \
./lib/src/isgraph.pp \
./lib/src/islower.pp \
./lib/src/isprint.pp \
./lib/src/ispunct.pp \
./lib/src/isspace.pp \
./lib/src/isupper.pp \
./lib/src/isxdigit.pp \
./lib/src/ldexp.pp \
./lib/src/lldiv.pp \
./lib/src/localtim.pp \
./lib/src/log.pp \
./lib/src/log10.pp \
./lib/src/lowlev.pp \
./lib/src/ltoa.pp \
./lib/src/memccpy.pp \
./lib/src/memchr.pp \
./lib/src/memcmp.pp \
./lib/src/memcpy.pp \
./lib/src/memcpy_ff.pp \
./lib/src/memcpy_fn.pp \
./lib/src/memcpy_nf.pp \
./lib/src/memcpy_nn.pp \
./lib/src/memmov.pp \
./lib/src/memory.pp \
./lib/src/memset.pp \
./lib/src/mktime.pp \
./lib/src/modf.pp \
./lib/src/multibyte.pp \
./lib/src/perror.pp \
./lib/src/pow.pp \
./lib/src/printf.pp \
./lib/src/qsort.pp \
./lib/src/raise.pp \
./lib/src/rand.pp \
./lib/src/remove.pp \
./lib/src/rewind.pp \
./lib/src/rindex.pp \
./lib/src/setbuf.pp \
./lib/src/setlocale.pp \
./lib/src/setvbuf.pp \
./lib/src/signal.pp \
./lib/src/sin.pp \
./lib/src/sinh.pp \
./lib/src/sinit.pp \
./lib/src/snprintf.pp \
./lib/src/sprintf.pp \
./lib/src/sqrt.pp \
./lib/src/sscanf.pp \
./lib/src/stox.pp \
./lib/src/strcasecmp.pp \
./lib/src/strcat.pp \
./lib/src/strchr.pp \
./lib/src/strcmp.pp \
./lib/src/strcoll.pp \
./lib/src/strcpy.pp \
./lib/src/strcspn.pp \
./lib/src/strdup.pp \
./lib/src/strerror.pp \
./lib/src/strftime.pp \
./lib/src/strlen.pp \
./lib/src/strncasecmp.pp \
./lib/src/strncat.pp \
./lib/src/strncmp.pp \
./lib/src/strncpy.pp \
./lib/src/strpbrk.pp \
./lib/src/strrchr.pp \
./lib/src/strspn.pp \
./lib/src/strstr.pp \
./lib/src/strtod.pp \
./lib/src/strtoimax.pp \
./lib/src/strtok.pp \
./lib/src/strtol.pp \
./lib/src/strtold.pp \
./lib/src/strtoll.pp \
./lib/src/strtoul.pp \
./lib/src/strtoull.pp \
./lib/src/strtoumax.pp \
./lib/src/strxfrm.pp \
./lib/src/tan.pp \
./lib/src/tanh.pp \
./lib/src/time.pp \
./lib/src/tmpfile.pp \
./lib/src/tmpnam.pp \
./lib/src/tmzone.pp \
./lib/src/toascii.pp \
./lib/src/tolower.pp \
./lib/src/toupper.pp \
./lib/src/trgdrv.pp \
./lib/src/ungetc.pp \
./lib/src/vfprintf.pp \
./lib/src/vprintf.pp \
./lib/src/vsnprintf.pp \
./lib/src/vsprintf.pp \
./lib/src/wctype.pp 

CPP_DEPS__QUOTED += \
"lib\src\array_del.pp" \
"lib\src\array_new.pp" \
"lib\src\array_nodel.pp" \
"lib\src\array_nonew.pp" \
"lib\src\array_pdel.pp" \
"lib\src\array_pnew.pp" \
"lib\src\delete.pp" \
"lib\src\delnothrow.pp" \
"lib\src\dtor_list.pp" \
"lib\src\eh_util.pp" \
"lib\src\error.pp" \
"lib\src\fiopen.pp" \
"lib\src\guard.pp" \
"lib\src\iomanip.pp" \
"lib\src\ios.pp" \
"lib\src\iostream.pp" \
"lib\src\limits.pp" \
"lib\src\locale.pp" \
"lib\src\locale0.pp" \
"lib\src\memzero.pp" \
"lib\src\new_.pp" \
"lib\src\newhandler.pp" \
"lib\src\newnothrow.pp" \
"lib\src\nothrow.pp" \
"lib\src\placedel.pp" \
"lib\src\placenew.pp" \
"lib\src\pure_virt.pp" \
"lib\src\raisehan.pp" \
"lib\src\rtti.pp" \
"lib\src\set_new.pp" \
"lib\src\string.pp" \
"lib\src\strstrea.pp" \
"lib\src\throw.pp" \
"lib\src\throw_edg.pp" \
"lib\src\typeinfo_.pp" \
"lib\src\vars.pp" \
"lib\src\vec_cctor.pp" \
"lib\src\vec_newdel.pp" \
"lib\src\vla_alloc.pp" \
"lib\src\wiostrea.pp" \
"lib\src\wlocale.pp" \
"lib\src\xfpostox.pp" \
"lib\src\xlocale.pp" \
"lib\src\xlocinfo.pp" 

C_DEPS__QUOTED += \
"lib\src\_bufread.pp" \
"lib\src\_data_synch.pp" \
"lib\src\_io_perm.pp" \
"lib\src\_lock.pp" \
"lib\src\_log.pp" \
"lib\src\_mutex.pp" \
"lib\src\_printfi.pp" \
"lib\src\_printfi_min.pp" \
"lib\src\_printfi_nf.pp" \
"lib\src\_pthread.pp" \
"lib\src\_scanfi.pp" \
"lib\src\_scanfi_min.pp" \
"lib\src\_scanfi_nf.pp" \
"lib\src\_tvaltostr.pp" \
"lib\src\abs.pp" \
"lib\src\acos.pp" \
"lib\src\ankmsg.pp" \
"lib\src\args_main.pp" \
"lib\src\asctime.pp" \
"lib\src\asin.pp" \
"lib\src\assert.pp" \
"lib\src\atan.pp" \
"lib\src\atan2.pp" \
"lib\src\atexit.pp" \
"lib\src\atof.pp" \
"lib\src\atoi.pp" \
"lib\src\atol.pp" \
"lib\src\atoll.pp" \
"lib\src\bcmp.pp" \
"lib\src\bcopy.pp" \
"lib\src\bsearch.pp" \
"lib\src\bzero.pp" \
"lib\src\clearerr.pp" \
"lib\src\clock.pp" \
"lib\src\cos.pp" \
"lib\src\cosh.pp" \
"lib\src\cpy_tbl.pp" \
"lib\src\ctime_.pp" \
"lib\src\ctype.pp" \
"lib\src\defs.pp" \
"lib\src\difftime.pp" \
"lib\src\div.pp" \
"lib\src\ecvt.pp" \
"lib\src\errno.pp" \
"lib\src\exit.pp" \
"lib\src\exp.pp" \
"lib\src\fabs.pp" \
"lib\src\far_cpy_tbl.pp" \
"lib\src\faratof.pp" \
"lib\src\faratoi.pp" \
"lib\src\farbsearch.pp" \
"lib\src\farfrexp.pp" \
"lib\src\farltoa.pp" \
"lib\src\farmemchr.pp" \
"lib\src\farmemcmp.pp" \
"lib\src\farmemmov.pp" \
"lib\src\farmemory.pp" \
"lib\src\farmemset.pp" \
"lib\src\farmodf.pp" \
"lib\src\farqsort.pp" \
"lib\src\farstrcat.pp" \
"lib\src\farstrchr.pp" \
"lib\src\farstrcmp.pp" \
"lib\src\farstrcoll.pp" \
"lib\src\farstrcpy.pp" \
"lib\src\farstrcspn.pp" \
"lib\src\farstrerror.pp" \
"lib\src\farstrlen.pp" \
"lib\src\farstrncat.pp" \
"lib\src\farstrncmp.pp" \
"lib\src\farstrncpy.pp" \
"lib\src\farstrpbrk.pp" \
"lib\src\farstrrchr.pp" \
"lib\src\farstrspn.pp" \
"lib\src\farstrstr.pp" \
"lib\src\farstrtod.pp" \
"lib\src\farstrtok.pp" \
"lib\src\farstrtol.pp" \
"lib\src\farstrtold.pp" \
"lib\src\farstrtoll.pp" \
"lib\src\farstrtoul.pp" \
"lib\src\farstrtoull.pp" \
"lib\src\farstrxfrm.pp" \
"lib\src\fclose.pp" \
"lib\src\fcvt.pp" \
"lib\src\feof.pp" \
"lib\src\ferror.pp" \
"lib\src\fflush.pp" \
"lib\src\ffs.pp" \
"lib\src\fgetc.pp" \
"lib\src\fgetpos.pp" \
"lib\src\fgets.pp" \
"lib\src\fmod.pp" \
"lib\src\fopen.pp" \
"lib\src\fprintf.pp" \
"lib\src\fputc.pp" \
"lib\src\fputs.pp" \
"lib\src\fread.pp" \
"lib\src\frexp.pp" \
"lib\src\fscanf.pp" \
"lib\src\fseek.pp" \
"lib\src\fsetpos.pp" \
"lib\src\ftell.pp" \
"lib\src\fwide.pp" \
"lib\src\fwrite.pp" \
"lib\src\getenv.pp" \
"lib\src\gmtime.pp" \
"lib\src\imaxabs.pp" \
"lib\src\imaxdiv.pp" \
"lib\src\index.pp" \
"lib\src\isalnum.pp" \
"lib\src\isalpha.pp" \
"lib\src\isascii.pp" \
"lib\src\iscntrl.pp" \
"lib\src\isdigit.pp" \
"lib\src\isgraph.pp" \
"lib\src\islower.pp" \
"lib\src\isprint.pp" \
"lib\src\ispunct.pp" \
"lib\src\isspace.pp" \
"lib\src\isupper.pp" \
"lib\src\isxdigit.pp" \
"lib\src\ldexp.pp" \
"lib\src\lldiv.pp" \
"lib\src\localtim.pp" \
"lib\src\log.pp" \
"lib\src\log10.pp" \
"lib\src\lowlev.pp" \
"lib\src\ltoa.pp" \
"lib\src\memccpy.pp" \
"lib\src\memchr.pp" \
"lib\src\memcmp.pp" \
"lib\src\memcpy.pp" \
"lib\src\memcpy_ff.pp" \
"lib\src\memcpy_fn.pp" \
"lib\src\memcpy_nf.pp" \
"lib\src\memcpy_nn.pp" \
"lib\src\memmov.pp" \
"lib\src\memory.pp" \
"lib\src\memset.pp" \
"lib\src\mktime.pp" \
"lib\src\modf.pp" \
"lib\src\multibyte.pp" \
"lib\src\perror.pp" \
"lib\src\pow.pp" \
"lib\src\printf.pp" \
"lib\src\qsort.pp" \
"lib\src\raise.pp" \
"lib\src\rand.pp" \
"lib\src\remove.pp" \
"lib\src\rewind.pp" \
"lib\src\rindex.pp" \
"lib\src\setbuf.pp" \
"lib\src\setlocale.pp" \
"lib\src\setvbuf.pp" \
"lib\src\signal.pp" \
"lib\src\sin.pp" \
"lib\src\sinh.pp" \
"lib\src\sinit.pp" \
"lib\src\snprintf.pp" \
"lib\src\sprintf.pp" \
"lib\src\sqrt.pp" \
"lib\src\sscanf.pp" \
"lib\src\stox.pp" \
"lib\src\strcasecmp.pp" \
"lib\src\strcat.pp" \
"lib\src\strchr.pp" \
"lib\src\strcmp.pp" \
"lib\src\strcoll.pp" \
"lib\src\strcpy.pp" \
"lib\src\strcspn.pp" \
"lib\src\strdup.pp" \
"lib\src\strerror.pp" \
"lib\src\strftime.pp" \
"lib\src\strlen.pp" \
"lib\src\strncasecmp.pp" \
"lib\src\strncat.pp" \
"lib\src\strncmp.pp" \
"lib\src\strncpy.pp" \
"lib\src\strpbrk.pp" \
"lib\src\strrchr.pp" \
"lib\src\strspn.pp" \
"lib\src\strstr.pp" \
"lib\src\strtod.pp" \
"lib\src\strtoimax.pp" \
"lib\src\strtok.pp" \
"lib\src\strtol.pp" \
"lib\src\strtold.pp" \
"lib\src\strtoll.pp" \
"lib\src\strtoul.pp" \
"lib\src\strtoull.pp" \
"lib\src\strtoumax.pp" \
"lib\src\strxfrm.pp" \
"lib\src\tan.pp" \
"lib\src\tanh.pp" \
"lib\src\time.pp" \
"lib\src\tmpfile.pp" \
"lib\src\tmpnam.pp" \
"lib\src\tmzone.pp" \
"lib\src\toascii.pp" \
"lib\src\tolower.pp" \
"lib\src\toupper.pp" \
"lib\src\trgdrv.pp" \
"lib\src\ungetc.pp" \
"lib\src\vfprintf.pp" \
"lib\src\vprintf.pp" \
"lib\src\vsnprintf.pp" \
"lib\src\vsprintf.pp" \
"lib\src\wctype.pp" 

OBJS__QUOTED += \
"lib\src\IQ.obj" \
"lib\src\IQxmpy.obj" \
"lib\src\_bufread.obj" \
"lib\src\_data_synch.obj" \
"lib\src\_io_perm.obj" \
"lib\src\_lock.obj" \
"lib\src\_log.obj" \
"lib\src\_mutex.obj" \
"lib\src\_printfi.obj" \
"lib\src\_printfi_min.obj" \
"lib\src\_printfi_nf.obj" \
"lib\src\_pthread.obj" \
"lib\src\_scanfi.obj" \
"lib\src\_scanfi_min.obj" \
"lib\src\_scanfi_nf.obj" \
"lib\src\_tvaltostr.obj" \
"lib\src\abs.obj" \
"lib\src\abstract.obj" \
"lib\src\acos.obj" \
"lib\src\ankmsg.obj" \
"lib\src\args_main.obj" \
"lib\src\array_del.obj" \
"lib\src\array_new.obj" \
"lib\src\array_nodel.obj" \
"lib\src\array_nonew.obj" \
"lib\src\array_pdel.obj" \
"lib\src\array_pnew.obj" \
"lib\src\asctime.obj" \
"lib\src\asin.obj" \
"lib\src\assert.obj" \
"lib\src\atan.obj" \
"lib\src\atan2.obj" \
"lib\src\atexit.obj" \
"lib\src\atof.obj" \
"lib\src\atoi.obj" \
"lib\src\atol.obj" \
"lib\src\atoll.obj" \
"lib\src\bcmp.obj" \
"lib\src\bcopy.obj" \
"lib\src\boot.obj" \
"lib\src\bsearch.obj" \
"lib\src\bzero.obj" \
"lib\src\clearerr.obj" \
"lib\src\clock.obj" \
"lib\src\cos.obj" \
"lib\src\cosh.obj" \
"lib\src\cpy_tbl.obj" \
"lib\src\cpy_utils.obj" \
"lib\src\ctime_.obj" \
"lib\src\ctype.obj" \
"lib\src\defs.obj" \
"lib\src\delete.obj" \
"lib\src\delnothrow.obj" \
"lib\src\difftime.obj" \
"lib\src\div.obj" \
"lib\src\dtor_list.obj" \
"lib\src\ecvt.obj" \
"lib\src\eh_util.obj" \
"lib\src\epilog.obj" \
"lib\src\errno.obj" \
"lib\src\error.obj" \
"lib\src\exit.obj" \
"lib\src\exp.obj" \
"lib\src\fabs.obj" \
"lib\src\far_cpy_tbl.obj" \
"lib\src\faratof.obj" \
"lib\src\faratoi.obj" \
"lib\src\farbsearch.obj" \
"lib\src\farfrexp.obj" \
"lib\src\farltoa.obj" \
"lib\src\farmemchr.obj" \
"lib\src\farmemcmp.obj" \
"lib\src\farmemmov.obj" \
"lib\src\farmemory.obj" \
"lib\src\farmemset.obj" \
"lib\src\farmodf.obj" \
"lib\src\farqsort.obj" \
"lib\src\farsetjmp.obj" \
"lib\src\farstrcat.obj" \
"lib\src\farstrchr.obj" \
"lib\src\farstrcmp.obj" \
"lib\src\farstrcoll.obj" \
"lib\src\farstrcpy.obj" \
"lib\src\farstrcspn.obj" \
"lib\src\farstrerror.obj" \
"lib\src\farstrlen.obj" \
"lib\src\farstrncat.obj" \
"lib\src\farstrncmp.obj" \
"lib\src\farstrncpy.obj" \
"lib\src\farstrpbrk.obj" \
"lib\src\farstrrchr.obj" \
"lib\src\farstrspn.obj" \
"lib\src\farstrstr.obj" \
"lib\src\farstrtod.obj" \
"lib\src\farstrtok.obj" \
"lib\src\farstrtol.obj" \
"lib\src\farstrtold.obj" \
"lib\src\farstrtoll.obj" \
"lib\src\farstrtoul.obj" \
"lib\src\farstrtoull.obj" \
"lib\src\farstrxfrm.obj" \
"lib\src\fclose.obj" \
"lib\src\fcvt.obj" \
"lib\src\fd_add.obj" \
"lib\src\fd_cmp.obj" \
"lib\src\fd_div.obj" \
"lib\src\fd_mpy.obj" \
"lib\src\fd_neg.obj" \
"lib\src\fd_sub.obj" \
"lib\src\fd_tofs.obj" \
"lib\src\fd_toi.obj" \
"lib\src\fd_tol.obj" \
"lib\src\fd_toll.obj" \
"lib\src\fd_tou.obj" \
"lib\src\fd_toul.obj" \
"lib\src\fd_toull.obj" \
"lib\src\feof.obj" \
"lib\src\ferror.obj" \
"lib\src\fflush.obj" \
"lib\src\ffs.obj" \
"lib\src\fgetc.obj" \
"lib\src\fgetpos.obj" \
"lib\src\fgets.obj" \
"lib\src\fiopen.obj" \
"lib\src\fmod.obj" \
"lib\src\fopen.obj" \
"lib\src\fprintf.obj" \
"lib\src\fputc.obj" \
"lib\src\fputs.obj" \
"lib\src\fread.obj" \
"lib\src\frexp.obj" \
"lib\src\fs_add.obj" \
"lib\src\fs_cmp.obj" \
"lib\src\fs_div.obj" \
"lib\src\fs_mpy.obj" \
"lib\src\fs_neg.obj" \
"lib\src\fs_tofd.obj" \
"lib\src\fs_toi.obj" \
"lib\src\fs_tol.obj" \
"lib\src\fs_toll.obj" \
"lib\src\fs_tou.obj" \
"lib\src\fs_toul.obj" \
"lib\src\fs_toull.obj" \
"lib\src\fscanf.obj" \
"lib\src\fseek.obj" \
"lib\src\fsetpos.obj" \
"lib\src\ftell.obj" \
"lib\src\fwide.obj" \
"lib\src\fwrite.obj" \
"lib\src\getenv.obj" \
"lib\src\gmtime.obj" \
"lib\src\guard.obj" \
"lib\src\i_div.obj" \
"lib\src\i_tofd.obj" \
"lib\src\i_tofs.obj" \
"lib\src\imaxabs.obj" \
"lib\src\imaxdiv.obj" \
"lib\src\index.obj" \
"lib\src\iomanip.obj" \
"lib\src\ios.obj" \
"lib\src\iostream.obj" \
"lib\src\isalnum.obj" \
"lib\src\isalpha.obj" \
"lib\src\isascii.obj" \
"lib\src\iscntrl.obj" \
"lib\src\isdigit.obj" \
"lib\src\isgraph.obj" \
"lib\src\islower.obj" \
"lib\src\isprint.obj" \
"lib\src\ispunct.obj" \
"lib\src\isspace.obj" \
"lib\src\isupper.obj" \
"lib\src\isxdigit.obj" \
"lib\src\l_div.obj" \
"lib\src\l_lsl.obj" \
"lib\src\l_lsr.obj" \
"lib\src\l_mpy.obj" \
"lib\src\l_tofd.obj" \
"lib\src\l_tofs.obj" \
"lib\src\ldexp.obj" \
"lib\src\limits.obj" \
"lib\src\ll_abs.obj" \
"lib\src\ll_aox.obj" \
"lib\src\ll_cmp.obj" \
"lib\src\ll_div.obj" \
"lib\src\ll_mpy.obj" \
"lib\src\ll_tofd.obj" \
"lib\src\ll_tofs.obj" \
"lib\src\lldiv.obj" \
"lib\src\locale.obj" \
"lib\src\locale0.obj" \
"lib\src\localtim.obj" \
"lib\src\log.obj" \
"lib\src\log10.obj" \
"lib\src\lowlev.obj" \
"lib\src\ltoa.obj" \
"lib\src\memccpy.obj" \
"lib\src\memchr.obj" \
"lib\src\memcmp.obj" \
"lib\src\memcpy.obj" \
"lib\src\memcpy_ff.obj" \
"lib\src\memcpy_fn.obj" \
"lib\src\memcpy_nf.obj" \
"lib\src\memcpy_nn.obj" \
"lib\src\memmov.obj" \
"lib\src\memory.obj" \
"lib\src\memset.obj" \
"lib\src\memzero.obj" \
"lib\src\mktime.obj" \
"lib\src\modf.obj" \
"lib\src\multibyte.obj" \
"lib\src\new_.obj" \
"lib\src\newhandler.obj" \
"lib\src\newnothrow.obj" \
"lib\src\nothrow.obj" \
"lib\src\perror.obj" \
"lib\src\placedel.obj" \
"lib\src\placenew.obj" \
"lib\src\pow.obj" \
"lib\src\printf.obj" \
"lib\src\prolog.obj" \
"lib\src\pure_virt.obj" \
"lib\src\qsort.obj" \
"lib\src\raise.obj" \
"lib\src\raisehan.obj" \
"lib\src\rand.obj" \
"lib\src\remove.obj" \
"lib\src\rewind.obj" \
"lib\src\rindex.obj" \
"lib\src\rtti.obj" \
"lib\src\set_new.obj" \
"lib\src\setbuf.obj" \
"lib\src\setjmp.obj" \
"lib\src\setlocale.obj" \
"lib\src\setvbuf.obj" \
"lib\src\signal.obj" \
"lib\src\sin.obj" \
"lib\src\sinh.obj" \
"lib\src\sinit.obj" \
"lib\src\snprintf.obj" \
"lib\src\sprintf.obj" \
"lib\src\sqrt.obj" \
"lib\src\sscanf.obj" \
"lib\src\stox.obj" \
"lib\src\strcasecmp.obj" \
"lib\src\strcat.obj" \
"lib\src\strchr.obj" \
"lib\src\strcmp.obj" \
"lib\src\strcoll.obj" \
"lib\src\strcpy.obj" \
"lib\src\strcspn.obj" \
"lib\src\strdup.obj" \
"lib\src\strerror.obj" \
"lib\src\strftime.obj" \
"lib\src\string.obj" \
"lib\src\strlen.obj" \
"lib\src\strncasecmp.obj" \
"lib\src\strncat.obj" \
"lib\src\strncmp.obj" \
"lib\src\strncpy.obj" \
"lib\src\strpbrk.obj" \
"lib\src\strrchr.obj" \
"lib\src\strspn.obj" \
"lib\src\strstr.obj" \
"lib\src\strstrea.obj" \
"lib\src\strtod.obj" \
"lib\src\strtoimax.obj" \
"lib\src\strtok.obj" \
"lib\src\strtol.obj" \
"lib\src\strtold.obj" \
"lib\src\strtoll.obj" \
"lib\src\strtoul.obj" \
"lib\src\strtoull.obj" \
"lib\src\strtoumax.obj" \
"lib\src\strxfrm.obj" \
"lib\src\tan.obj" \
"lib\src\tanh.obj" \
"lib\src\throw.obj" \
"lib\src\throw_edg.obj" \
"lib\src\time.obj" \
"lib\src\tmpfile.obj" \
"lib\src\tmpnam.obj" \
"lib\src\tmzone.obj" \
"lib\src\toascii.obj" \
"lib\src\tolower.obj" \
"lib\src\toupper.obj" \
"lib\src\trgdrv.obj" \
"lib\src\typeinfo_.obj" \
"lib\src\u_div.obj" \
"lib\src\u_tofd.obj" \
"lib\src\u_tofs.obj" \
"lib\src\ul_lsr.obj" \
"lib\src\ul_tofd.obj" \
"lib\src\ul_tofs.obj" \
"lib\src\ull_tofd.obj" \
"lib\src\ull_tofs.obj" \
"lib\src\ungetc.obj" \
"lib\src\vars.obj" \
"lib\src\vec_cctor.obj" \
"lib\src\vec_newdel.obj" \
"lib\src\vfprintf.obj" \
"lib\src\vla_alloc.obj" \
"lib\src\vprintf.obj" \
"lib\src\vsnprintf.obj" \
"lib\src\vsprintf.obj" \
"lib\src\wctype.obj" \
"lib\src\wiostrea.obj" \
"lib\src\wlocale.obj" \
"lib\src\xfpostox.obj" \
"lib\src\xlocale.obj" \
"lib\src\xlocinfo.obj" 

ASM_DEPS__QUOTED += \
"lib\src\IQ.pp" \
"lib\src\IQxmpy.pp" \
"lib\src\abstract.pp" \
"lib\src\boot.pp" \
"lib\src\cpy_utils.pp" \
"lib\src\epilog.pp" \
"lib\src\farsetjmp.pp" \
"lib\src\fd_add.pp" \
"lib\src\fd_cmp.pp" \
"lib\src\fd_div.pp" \
"lib\src\fd_mpy.pp" \
"lib\src\fd_neg.pp" \
"lib\src\fd_sub.pp" \
"lib\src\fd_tofs.pp" \
"lib\src\fd_toi.pp" \
"lib\src\fd_tol.pp" \
"lib\src\fd_toll.pp" \
"lib\src\fd_tou.pp" \
"lib\src\fd_toul.pp" \
"lib\src\fd_toull.pp" \
"lib\src\fs_add.pp" \
"lib\src\fs_cmp.pp" \
"lib\src\fs_div.pp" \
"lib\src\fs_mpy.pp" \
"lib\src\fs_neg.pp" \
"lib\src\fs_tofd.pp" \
"lib\src\fs_toi.pp" \
"lib\src\fs_tol.pp" \
"lib\src\fs_toll.pp" \
"lib\src\fs_tou.pp" \
"lib\src\fs_toul.pp" \
"lib\src\fs_toull.pp" \
"lib\src\i_div.pp" \
"lib\src\i_tofd.pp" \
"lib\src\i_tofs.pp" \
"lib\src\l_div.pp" \
"lib\src\l_lsl.pp" \
"lib\src\l_lsr.pp" \
"lib\src\l_mpy.pp" \
"lib\src\l_tofd.pp" \
"lib\src\l_tofs.pp" \
"lib\src\ll_abs.pp" \
"lib\src\ll_aox.pp" \
"lib\src\ll_cmp.pp" \
"lib\src\ll_div.pp" \
"lib\src\ll_mpy.pp" \
"lib\src\ll_tofd.pp" \
"lib\src\ll_tofs.pp" \
"lib\src\prolog.pp" \
"lib\src\setjmp.pp" \
"lib\src\u_div.pp" \
"lib\src\u_tofd.pp" \
"lib\src\u_tofs.pp" \
"lib\src\ul_lsr.pp" \
"lib\src\ul_tofd.pp" \
"lib\src\ul_tofs.pp" \
"lib\src\ull_tofd.pp" \
"lib\src\ull_tofs.pp" 

ASM_SRCS__QUOTED += \
"../lib/src/IQ.asm" \
"../lib/src/IQxmpy.asm" \
"../lib/src/abstract.asm" \
"../lib/src/boot.asm" \
"../lib/src/cpy_utils.asm" \
"../lib/src/epilog.asm" \
"../lib/src/farsetjmp.asm" \
"../lib/src/fd_add.asm" \
"../lib/src/fd_cmp.asm" \
"../lib/src/fd_div.asm" \
"../lib/src/fd_mpy.asm" \
"../lib/src/fd_neg.asm" \
"../lib/src/fd_sub.asm" \
"../lib/src/fd_tofs.asm" \
"../lib/src/fd_toi.asm" \
"../lib/src/fd_tol.asm" \
"../lib/src/fd_toll.asm" \
"../lib/src/fd_tou.asm" \
"../lib/src/fd_toul.asm" \
"../lib/src/fd_toull.asm" \
"../lib/src/fs_add.asm" \
"../lib/src/fs_cmp.asm" \
"../lib/src/fs_div.asm" \
"../lib/src/fs_mpy.asm" \
"../lib/src/fs_neg.asm" \
"../lib/src/fs_tofd.asm" \
"../lib/src/fs_toi.asm" \
"../lib/src/fs_tol.asm" \
"../lib/src/fs_toll.asm" \
"../lib/src/fs_tou.asm" \
"../lib/src/fs_toul.asm" \
"../lib/src/fs_toull.asm" \
"../lib/src/i_div.asm" \
"../lib/src/i_tofd.asm" \
"../lib/src/i_tofs.asm" \
"../lib/src/l_div.asm" \
"../lib/src/l_lsl.asm" \
"../lib/src/l_lsr.asm" \
"../lib/src/l_mpy.asm" \
"../lib/src/l_tofd.asm" \
"../lib/src/l_tofs.asm" \
"../lib/src/ll_abs.asm" \
"../lib/src/ll_aox.asm" \
"../lib/src/ll_cmp.asm" \
"../lib/src/ll_div.asm" \
"../lib/src/ll_mpy.asm" \
"../lib/src/ll_tofd.asm" \
"../lib/src/ll_tofs.asm" \
"../lib/src/prolog.asm" \
"../lib/src/setjmp.asm" \
"../lib/src/u_div.asm" \
"../lib/src/u_tofd.asm" \
"../lib/src/u_tofs.asm" \
"../lib/src/ul_lsr.asm" \
"../lib/src/ul_tofd.asm" \
"../lib/src/ul_tofs.asm" \
"../lib/src/ull_tofd.asm" \
"../lib/src/ull_tofs.asm" 

C_SRCS__QUOTED += \
"../lib/src/_bufread.c" \
"../lib/src/_data_synch.c" \
"../lib/src/_io_perm.c" \
"../lib/src/_lock.c" \
"../lib/src/_log.c" \
"../lib/src/_mutex.c" \
"../lib/src/_printfi.c" \
"../lib/src/_printfi_min.c" \
"../lib/src/_printfi_nf.c" \
"../lib/src/_pthread.c" \
"../lib/src/_scanfi.c" \
"../lib/src/_scanfi_min.c" \
"../lib/src/_scanfi_nf.c" \
"../lib/src/_tvaltostr.c" \
"../lib/src/abs.c" \
"../lib/src/acos.c" \
"../lib/src/ankmsg.c" \
"../lib/src/args_main.c" \
"../lib/src/asctime.c" \
"../lib/src/asin.c" \
"../lib/src/assert.c" \
"../lib/src/atan.c" \
"../lib/src/atan2.c" \
"../lib/src/atexit.c" \
"../lib/src/atof.c" \
"../lib/src/atoi.c" \
"../lib/src/atol.c" \
"../lib/src/atoll.c" \
"../lib/src/bcmp.c" \
"../lib/src/bcopy.c" \
"../lib/src/bsearch.c" \
"../lib/src/bzero.c" \
"../lib/src/clearerr.c" \
"../lib/src/clock.c" \
"../lib/src/cos.c" \
"../lib/src/cosh.c" \
"../lib/src/cpy_tbl.c" \
"../lib/src/ctime_.c" \
"../lib/src/ctype.c" \
"../lib/src/defs.c" \
"../lib/src/difftime.c" \
"../lib/src/div.c" \
"../lib/src/ecvt.c" \
"../lib/src/errno.c" \
"../lib/src/exit.c" \
"../lib/src/exp.c" \
"../lib/src/fabs.c" \
"../lib/src/far_cpy_tbl.c" \
"../lib/src/faratof.c" \
"../lib/src/faratoi.c" \
"../lib/src/farbsearch.c" \
"../lib/src/farfrexp.c" \
"../lib/src/farltoa.c" \
"../lib/src/farmemchr.c" \
"../lib/src/farmemcmp.c" \
"../lib/src/farmemmov.c" \
"../lib/src/farmemory.c" \
"../lib/src/farmemset.c" \
"../lib/src/farmodf.c" \
"../lib/src/farqsort.c" \
"../lib/src/farstrcat.c" \
"../lib/src/farstrchr.c" \
"../lib/src/farstrcmp.c" \
"../lib/src/farstrcoll.c" \
"../lib/src/farstrcpy.c" \
"../lib/src/farstrcspn.c" \
"../lib/src/farstrerror.c" \
"../lib/src/farstrlen.c" \
"../lib/src/farstrncat.c" \
"../lib/src/farstrncmp.c" \
"../lib/src/farstrncpy.c" \
"../lib/src/farstrpbrk.c" \
"../lib/src/farstrrchr.c" \
"../lib/src/farstrspn.c" \
"../lib/src/farstrstr.c" \
"../lib/src/farstrtod.c" \
"../lib/src/farstrtok.c" \
"../lib/src/farstrtol.c" \
"../lib/src/farstrtold.c" \
"../lib/src/farstrtoll.c" \
"../lib/src/farstrtoul.c" \
"../lib/src/farstrtoull.c" \
"../lib/src/farstrxfrm.c" \
"../lib/src/fclose.c" \
"../lib/src/fcvt.c" \
"../lib/src/feof.c" \
"../lib/src/ferror.c" \
"../lib/src/fflush.c" \
"../lib/src/ffs.c" \
"../lib/src/fgetc.c" \
"../lib/src/fgetpos.c" \
"../lib/src/fgets.c" \
"../lib/src/fmod.c" \
"../lib/src/fopen.c" \
"../lib/src/fprintf.c" \
"../lib/src/fputc.c" \
"../lib/src/fputs.c" \
"../lib/src/fread.c" \
"../lib/src/frexp.c" \
"../lib/src/fscanf.c" \
"../lib/src/fseek.c" \
"../lib/src/fsetpos.c" \
"../lib/src/ftell.c" \
"../lib/src/fwide.c" \
"../lib/src/fwrite.c" \
"../lib/src/getenv.c" \
"../lib/src/gmtime.c" \
"../lib/src/imaxabs.c" \
"../lib/src/imaxdiv.c" \
"../lib/src/index.c" \
"../lib/src/isalnum.c" \
"../lib/src/isalpha.c" \
"../lib/src/isascii.c" \
"../lib/src/iscntrl.c" \
"../lib/src/isdigit.c" \
"../lib/src/isgraph.c" \
"../lib/src/islower.c" \
"../lib/src/isprint.c" \
"../lib/src/ispunct.c" \
"../lib/src/isspace.c" \
"../lib/src/isupper.c" \
"../lib/src/isxdigit.c" \
"../lib/src/ldexp.c" \
"../lib/src/lldiv.c" \
"../lib/src/localtim.c" \
"../lib/src/log.c" \
"../lib/src/log10.c" \
"../lib/src/lowlev.c" \
"../lib/src/ltoa.c" \
"../lib/src/memccpy.c" \
"../lib/src/memchr.c" \
"../lib/src/memcmp.c" \
"../lib/src/memcpy.c" \
"../lib/src/memcpy_ff.c" \
"../lib/src/memcpy_fn.c" \
"../lib/src/memcpy_nf.c" \
"../lib/src/memcpy_nn.c" \
"../lib/src/memmov.c" \
"../lib/src/memory.c" \
"../lib/src/memset.c" \
"../lib/src/mktime.c" \
"../lib/src/modf.c" \
"../lib/src/multibyte.c" \
"../lib/src/perror.c" \
"../lib/src/pow.c" \
"../lib/src/printf.c" \
"../lib/src/qsort.c" \
"../lib/src/raise.c" \
"../lib/src/rand.c" \
"../lib/src/remove.c" \
"../lib/src/rewind.c" \
"../lib/src/rindex.c" \
"../lib/src/setbuf.c" \
"../lib/src/setlocale.c" \
"../lib/src/setvbuf.c" \
"../lib/src/signal.c" \
"../lib/src/sin.c" \
"../lib/src/sinh.c" \
"../lib/src/sinit.c" \
"../lib/src/snprintf.c" \
"../lib/src/sprintf.c" \
"../lib/src/sqrt.c" \
"../lib/src/sscanf.c" \
"../lib/src/stox.c" \
"../lib/src/strcasecmp.c" \
"../lib/src/strcat.c" \
"../lib/src/strchr.c" \
"../lib/src/strcmp.c" \
"../lib/src/strcoll.c" \
"../lib/src/strcpy.c" \
"../lib/src/strcspn.c" \
"../lib/src/strdup.c" \
"../lib/src/strerror.c" \
"../lib/src/strftime.c" \
"../lib/src/strlen.c" \
"../lib/src/strncasecmp.c" \
"../lib/src/strncat.c" \
"../lib/src/strncmp.c" \
"../lib/src/strncpy.c" \
"../lib/src/strpbrk.c" \
"../lib/src/strrchr.c" \
"../lib/src/strspn.c" \
"../lib/src/strstr.c" \
"../lib/src/strtod.c" \
"../lib/src/strtoimax.c" \
"../lib/src/strtok.c" \
"../lib/src/strtol.c" \
"../lib/src/strtold.c" \
"../lib/src/strtoll.c" \
"../lib/src/strtoul.c" \
"../lib/src/strtoull.c" \
"../lib/src/strtoumax.c" \
"../lib/src/strxfrm.c" \
"../lib/src/tan.c" \
"../lib/src/tanh.c" \
"../lib/src/time.c" \
"../lib/src/tmpfile.c" \
"../lib/src/tmpnam.c" \
"../lib/src/tmzone.c" \
"../lib/src/toascii.c" \
"../lib/src/tolower.c" \
"../lib/src/toupper.c" \
"../lib/src/trgdrv.c" \
"../lib/src/ungetc.c" \
"../lib/src/vfprintf.c" \
"../lib/src/vprintf.c" \
"../lib/src/vsnprintf.c" \
"../lib/src/vsprintf.c" \
"../lib/src/wctype.c" 

CPP_SRCS__QUOTED += \
"../lib/src/array_del.cpp" \
"../lib/src/array_new.cpp" \
"../lib/src/array_nodel.cpp" \
"../lib/src/array_nonew.cpp" \
"../lib/src/array_pdel.cpp" \
"../lib/src/array_pnew.cpp" \
"../lib/src/delete.cpp" \
"../lib/src/delnothrow.cpp" \
"../lib/src/dtor_list.cpp" \
"../lib/src/eh_util.cpp" \
"../lib/src/error.cpp" \
"../lib/src/fiopen.cpp" \
"../lib/src/guard.cpp" \
"../lib/src/iomanip.cpp" \
"../lib/src/ios.cpp" \
"../lib/src/iostream.cpp" \
"../lib/src/limits.cpp" \
"../lib/src/locale.cpp" \
"../lib/src/locale0.cpp" \
"../lib/src/memzero.cpp" \
"../lib/src/new_.cpp" \
"../lib/src/newhandler.cpp" \
"../lib/src/newnothrow.cpp" \
"../lib/src/nothrow.cpp" \
"../lib/src/placedel.cpp" \
"../lib/src/placenew.cpp" \
"../lib/src/pure_virt.cpp" \
"../lib/src/raisehan.cpp" \
"../lib/src/rtti.cpp" \
"../lib/src/set_new.cpp" \
"../lib/src/string.cpp" \
"../lib/src/strstrea.cpp" \
"../lib/src/throw.cpp" \
"../lib/src/throw_edg.cpp" \
"../lib/src/typeinfo_.cpp" \
"../lib/src/vars.cpp" \
"../lib/src/vec_cctor.cpp" \
"../lib/src/vec_newdel.cpp" \
"../lib/src/vla_alloc.cpp" \
"../lib/src/wiostrea.cpp" \
"../lib/src/wlocale.cpp" \
"../lib/src/xfpostox.cpp" \
"../lib/src/xlocale.cpp" \
"../lib/src/xlocinfo.cpp" 


